name: wolwo
description: An opensource wallpaper app built using flutter and unsplash API.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^0.3.3 #latest version
  random_color: ^1.0.5
  google_fonts: ^1.1.0
  url_launcher: ^5.4.11
  slimy_card: ^1.0.4
  device_info: ^0.4.2+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^0.1.3
  # image loading
  cached_network_image: ^2.2.0+1
  # zoom images
  photo_view: ^0.9.2
  # format date
  date_format: ^1.0.8
  # display images in staggered grid
  flutter_staggered_grid_view: ^0.3.0
  # sliding_up_panel: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  # ios: true
  # android: true
  # image_path_ios: "assets/launcher/icon.png"
  # image_path_android: "assets/launcher/icon.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # - assets/images/
    - assets/images/person.png
  #   - assets/steve-johnson.jpeg
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #     - asset: fonts/SF-Pro-Display-Ultralight.otf
  #       weight: 100
  #     - asset: fonts/SF-Pro-Display-Thin.otf
  #       weight: 200
  #     - asset: fonts/SF-Pro-Display-Light.otf
  #       weight: 300
  #     - asset: fonts/SF-Pro-Display-Regular.otf
  #       weight: 400
  #     - asset: fonts/SF-Pro-Display-Medium.otf
  #       weight: 500
  #     - asset: fonts/SF-Pro-Display-Semibold.otf
  #       weight: 600
  #     - asset: fonts/SF-Pro-Display-Bold.otf
  #       weight: 700
  #     - asset: fonts/SF-Pro-Display-Heavy.otf
  #       weight: 800
  #     - asset: fonts/SF-Pro-Display-Black.otf
  #       weight: 900
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
